var movies = [{
        "vote_count": 3838,
        "id": 321612,
        "video": false,
        "vote_average": 6.8,
        "title": "Beauty and the Beast",
        "popularity": 220.680675,
        "poster_path": "/tWqifoYuwLETmmasnGHO7xBjEtt.jpg",
        "original_language": "en",
        "original_title": "Beauty and the Beast",
        "genre_ids": [
            10751,
            14,
            10749
        ],
        "backdrop_path": "/6aUWe0GSl69wMTSWWexsorMIvwU.jpg",
        "adult": false,
        "overview": "A live-action adaptation of Disney's version of the classic 'Beauty and the Beast' tale of a cursed prince and a beautiful young woman who helps him break the spell.",
        "release_date": "2017-03-16"
    },
    {
        "vote_count": 339,
        "id": 324852,
        "video": false,
        "vote_average": 6,
        "title": "Despicable Me 3",
        "popularity": 146.329357,
        "poster_path": "/5qcUGqWoWhEsoQwNUrtf3y3fcWn.jpg",
        "original_language": "en",
        "original_title": "Despicable Me 3",
        "genre_ids": [
            12,
            16,
            35,
            10751
        ],
        "backdrop_path": "/qslbZBJHUis8PL97Dy2Fsbq8QsA.jpg",
        "adult": false,
        "overview": "Gru and his wife Lucy must stop former '80s child star Balthazar Bratt from achieving world domination.",
        "release_date": "2017-06-29"
    },
    {
        "vote_count": 594,
        "id": 315635,
        "video": false,
        "vote_average": 7.5,
        "title": "Spider-Man: Homecoming",
        "popularity": 113.730475,
        "poster_path": "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
        "original_language": "en",
        "original_title": "Spider-Man: Homecoming",
        "genre_ids": [
            28,
            12,
            878
        ],
        "backdrop_path": "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
        "adult": false,
        "overview": "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
        "release_date": "2017-07-05"
    },
    {
        "vote_count": 2686,
        "id": 297762,
        "video": false,
        "vote_average": 7.1,
        "title": "Wonder Woman",
        "popularity": 82.304103,
        "poster_path": "/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
        "original_language": "en",
        "original_title": "Wonder Woman",
        "genre_ids": [
            28,
            12,
            14
        ],
        "backdrop_path": "/hA5oCgvgCxj5MEWcLpjXXTwEANF.jpg",
        "adult": false,
        "overview": "An Amazon princess comes to the world of Man to become the greatest of the female superheroes.",
        "release_date": "2017-05-30"
    },
    {
        "vote_count": 3631,
        "id": 119450,
        "video": false,
        "vote_average": 7.3,
        "title": "Dawn of the Planet of the Apes",
        "popularity": 82.303675,
        "poster_path": "/2EUAUIu5lHFlkj5FRryohlH6CRO.jpg",
        "original_language": "en",
        "original_title": "Dawn of the Planet of the Apes",
        "genre_ids": [
            878,
            28,
            18,
            53
        ],
        "backdrop_path": "/rjUl3pd1LHVOVfG4IGcyA1cId5l.jpg",
        "adult": false,
        "overview": "A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.",
        "release_date": "2014-06-26"
    },
    {
        "vote_count": 4602,
        "id": 263115,
        "video": false,
        "vote_average": 7.5,
        "title": "Logan",
        "popularity": 67.713878,
        "poster_path": "/9EXnebqbb7dOhONLPV9Tg2oh2KD.jpg",
        "original_language": "en",
        "original_title": "Logan",
        "genre_ids": [
            28,
            18,
            878
        ],
        "backdrop_path": "/5pAGnkFYSsFJ99ZxDIYnhQbQFXs.jpg",
        "adult": false,
        "overview": "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
        "release_date": "2017-02-28"
    },
    {
        "vote_count": 996,
        "id": 282035,
        "video": false,
        "vote_average": 5.2,
        "title": "The Mummy",
        "popularity": 55.476211,
        "poster_path": "/zxkY8byBnCsXodEYpK8tmwEGXBI.jpg",
        "original_language": "en",
        "original_title": "The Mummy",
        "genre_ids": [
            28,
            12,
            14,
            27,
            53
        ],
        "backdrop_path": "/qedJJ2z9oBYKxxO4Pp8qAkfgPst.jpg",
        "adult": false,
        "overview": "Though safely entombed in a crypt deep beneath the unforgiving desert, an ancient queen whose destiny was unjustly taken from her is awakened in our current day, bringing with her malevolence grown over millennia, and terrors that defy human comprehension.",
        "release_date": "2017-06-06"
    },
    {
        "vote_count": 607,
        "id": 335988,
        "video": false,
        "vote_average": 6.3,
        "title": "Transformers: The Last Knight",
        "popularity": 51.655521,
        "poster_path": "/f8Ng1Sgb3VLiSwAvrfKeQPzvlfr.jpg",
        "original_language": "en",
        "original_title": "Transformers: The Last Knight",
        "genre_ids": [
            28,
            878,
            53,
            12
        ],
        "backdrop_path": "/Ytv7P13rbwQ3mLpCAY8lBTqI5s.jpg",
        "adult": false,
        "overview": "Autobots and Decepticons are at war, with humans on the sidelines. Optimus Prime is gone. The key to saving our future lies buried in the secrets of the past, in the hidden history of Transformers on Earth.",
        "release_date": "2017-06-21"
    },
    {
        "vote_count": 2177,
        "id": 293167,
        "video": false,
        "vote_average": 6.1,
        "title": "Kong: Skull Island",
        "popularity": 48.943499,
        "poster_path": "/r2517Vz9EhDhj88qwbDVj8DCRZN.jpg",
        "original_language": "en",
        "original_title": "Kong: Skull Island",
        "genre_ids": [
            28,
            12,
            14
        ],
        "backdrop_path": "/pGwChWiAY1bdoxL79sXmaFBlYJH.jpg",
        "adult": false,
        "overview": "Explore the mysterious and dangerous home of the king of the apes as a team of explorers ventures deep inside the treacherous, primordial island.",
        "release_date": "2017-03-08"
    },
    {
        "vote_count": 4624,
        "id": 245891,
        "video": false,
        "vote_average": 6.9,
        "title": "John Wick",
        "popularity": 43.621405,
        "poster_path": "/5vHssUeVe25bMrof1HyaPyWgaP.jpg",
        "original_language": "en",
        "original_title": "John Wick",
        "genre_ids": [
            28,
            53
        ],
        "backdrop_path": "/mFb0ygcue4ITixDkdr7wm1Tdarx.jpg",
        "adult": false,
        "overview": "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
        "release_date": "2014-10-22"
    },
    {
        "vote_count": 8380,
        "id": 76341,
        "video": false,
        "vote_average": 7.2,
        "title": "Mad Max: Fury Road",
        "popularity": 41.354905,
        "poster_path": "/kqjL17yufvn9OVLyXYpvtyrFfak.jpg",
        "original_language": "en",
        "original_title": "Mad Max: Fury Road",
        "genre_ids": [
            28,
            12,
            878,
            53
        ],
        "backdrop_path": "/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg",
        "adult": false,
        "overview": "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order. There's Max, a man of action and a man of few words, who seeks peace of mind following the loss of his wife and child in the aftermath of the chaos. And Furiosa, a woman of action and a woman who believes her path to survival may be achieved if she can make it across the desert back to her childhood homeland.",
        "release_date": "2015-05-13"
    },
    {
        "vote_count": 1220,
        "id": 395992,
        "video": false,
        "vote_average": 6.2,
        "title": "Life",
        "popularity": 41.212696,
        "poster_path": "/h2mhfbEBGABSHo2vXG1ECMKAJa7.jpg",
        "original_language": "en",
        "original_title": "Life",
        "genre_ids": [
            27,
            878,
            53
        ],
        "backdrop_path": "/hES8wGmkxHa54z7hqUMpw5TIs09.jpg",
        "adult": false,
        "overview": "The six-member crew of the International Space Station is tasked with studying a sample from Mars that may be the first proof of extra-terrestrial life, which proves more intelligent than ever expected.",
        "release_date": "2017-03-23"
    },
    {
        "vote_count": 1604,
        "id": 166426,
        "video": false,
        "vote_average": 6.5,
        "title": "Pirates of the Caribbean: Dead Men Tell No Tales",
        "popularity": 41.140038,
        "poster_path": "/xbpSDU3p7YUGlu9Mr6Egg2Vweto.jpg",
        "original_language": "en",
        "original_title": "Pirates of the Caribbean: Dead Men Tell No Tales",
        "genre_ids": [
            28,
            12,
            35,
            14
        ],
        "backdrop_path": "/tZvdyLP2F6x2TTuh292ceH87qZT.jpg",
        "adult": false,
        "overview": "Thrust into an all-new adventure, a down-on-his-luck Capt. Jack Sparrow feels the winds of ill-fortune blowing even more strongly when deadly ghost sailors led by his old nemesis, the evil Capt. Salazar, escape from the Devil's Triangle. Jack's only hope of survival lies in seeking out the legendary Trident of Poseidon, but to find it, he must forge an uneasy alliance with a brilliant and beautiful astronomer and a headstrong young man in the British navy.",
        "release_date": "2017-05-23"
    },
    {
        "vote_count": 8223,
        "id": 118340,
        "video": false,
        "vote_average": 7.8,
        "title": "Guardians of the Galaxy",
        "popularity": 39.437367,
        "poster_path": "/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg",
        "original_language": "en",
        "original_title": "Guardians of the Galaxy",
        "genre_ids": [
            28,
            878,
            12
        ],
        "backdrop_path": "/bHarw8xrmQeqf3t8HpuMY7zoK4x.jpg",
        "adult": false,
        "overview": "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
        "release_date": "2014-07-30"
    },
    {
        "vote_count": 2837,
        "id": 337339,
        "video": false,
        "vote_average": 6.8,
        "title": "The Fate of the Furious",
        "popularity": 39.014829,
        "poster_path": "/iNpz2DgTsTMPaDRZq2tnbqjL2vF.jpg",
        "original_language": "en",
        "original_title": "The Fate of the Furious",
        "genre_ids": [
            28,
            80,
            53
        ],
        "backdrop_path": "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
        "adult": false,
        "overview": "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
        "release_date": "2017-04-12"
    },
    {
        "vote_count": 1458,
        "id": 126889,
        "video": false,
        "vote_average": 5.8,
        "title": "Alien: Covenant",
        "popularity": 38.280206,
        "poster_path": "/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg",
        "original_language": "en",
        "original_title": "Alien: Covenant",
        "genre_ids": [
            27,
            878,
            53
        ],
        "backdrop_path": "/kMU8trT43p5LFoJ4plIySMOsZ1T.jpg",
        "adult": false,
        "overview": "Bound for a remote planet on the far side of the galaxy, the crew of the colony ship Covenant discovers what they think is an uncharted paradise, but is actually a dark, dangerous world — whose sole inhabitant is the “synthetic” David, survivor of the doomed Prometheus expedition.",
        "release_date": "2017-05-09"
    },
    {
        "vote_count": 7733,
        "id": 135397,
        "video": false,
        "vote_average": 6.5,
        "title": "Jurassic World",
        "popularity": 37.198215,
        "poster_path": "/jjBgi2r5cRt36xF6iNUEhzscEcb.jpg",
        "original_language": "en",
        "original_title": "Jurassic World",
        "genre_ids": [
            28,
            12,
            878,
            53
        ],
        "backdrop_path": "/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
        "adult": false,
        "overview": "Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.",
        "release_date": "2015-06-09"
    },
    {
        "vote_count": 6059,
        "id": 22,
        "video": false,
        "vote_average": 7.4,
        "title": "Pirates of the Caribbean: The Curse of the Black Pearl",
        "popularity": 34.303853,
        "poster_path": "/tkt9xR1kNX5R9rCebASKck44si2.jpg",
        "original_language": "en",
        "original_title": "Pirates of the Caribbean: The Curse of the Black Pearl",
        "genre_ids": [
            12,
            14,
            28
        ],
        "backdrop_path": "/8AUQ7YlJJA9C8kWk8P4YNHIcFDE.jpg",
        "adult": false,
        "overview": "Jack Sparrow, a freewheeling 17th-century pirate who roams the Caribbean Sea, butts heads with a rival pirate bent on pillaging the village of Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her. But their seafaring mission is hardly simple.",
        "release_date": "2003-07-09"
    },
    {
        "vote_count": 37,
        "id": 281338,
        "video": false,
        "vote_average": 6,
        "title": "War for the Planet of the Apes",
        "popularity": 33.620069,
        "poster_path": "/y52mjaCLoJJzxfcDDlksKDngiDx.jpg",
        "original_language": "en",
        "original_title": "War for the Planet of the Apes",
        "genre_ids": [
            28,
            12,
            18,
            878
        ],
        "backdrop_path": "/w4ZYFLJbiqZyvCcGHgvaHD6lTqQ.jpg",
        "adult": false,
        "overview": "Caesar and his apes are forced into a deadly conflict with an army of humans led by a ruthless Colonel. After the apes suffer unimaginable losses, Caesar wrestles with his darker instincts and begins his own mythic quest to avenge his kind. As the journey finally brings them face to face, Caesar and the Colonel are pitted against each other in an epic battle that will determine the fate of both their species and the future of the planet.",
        "release_date": "2017-07-13"
    },
    {
        "vote_count": 2813,
        "id": 283995,
        "video": false,
        "vote_average": 7.6,
        "title": "Guardians of the Galaxy Vol. 2",
        "popularity": 32.718841,
        "poster_path": "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
        "original_language": "en",
        "original_title": "Guardians of the Galaxy Vol. 2",
        "genre_ids": [
            28,
            12,
            35,
            878
        ],
        "backdrop_path": "/aJn9XeesqsrSLKcHfHP4u5985hn.jpg",
        "adult": false,
        "overview": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
        "release_date": "2017-04-19"
    },
    {
        "vote_count": 3603,
        "id": 61791,
        "video": false,
        "vote_average": 7,
        "title": "Rise of the Planet of the Apes",
        "popularity": 31.034124,
        "poster_path": "/esqXMJv6PiK7GJVRwd2FA3SZUoW.jpg",
        "original_language": "en",
        "original_title": "Rise of the Planet of the Apes",
        "genre_ids": [
            53,
            28,
            18,
            878
        ],
        "backdrop_path": "/caIpcr9xhvRcWfOMRDq3F5iIcLB.jpg",
        "adult": false,
        "overview": "Scientist Will Rodman is determined to find a cure for Alzheimer's, the disease which has slowly consumed his father. Will feels certain he is close to a breakthrough and tests his latest serum on apes, noticing dramatic increases in intelligence and brain activity in the primate subjects – especially Caesar, his pet chimpanzee.",
        "release_date": "2011-08-03"
    },
    {
        "vote_count": 830,
        "id": 305470,
        "video": false,
        "vote_average": 6.4,
        "title": "Power Rangers",
        "popularity": 30.878159,
        "poster_path": "/zV5rpeTzUJ7QpA3NC4iidlwXssU.jpg",
        "original_language": "en",
        "original_title": "Power Rangers",
        "genre_ids": [
            28,
            12,
            878
        ],
        "backdrop_path": "/gfTQaH7h09IaSZw9ubZgP2c7syr.jpg",
        "adult": false,
        "overview": "Saban's Power Rangers follows five ordinary teens who must become something extraordinary when they learn that their small town of Angel Grove — and the world — is on the verge of being obliterated by an alien threat. Chosen by destiny, our heroes quickly discover they are the only ones who can save the planet. But to do so, they will have to overcome their real-life issues and before it’s too late, band together as the Power Rangers.",
        "release_date": "2017-03-23"
    },
    {
        "vote_count": 9480,
        "id": 157336,
        "video": false,
        "vote_average": 8.1,
        "title": "Interstellar",
        "popularity": 25.862247,
        "poster_path": "/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg",
        "original_language": "en",
        "original_title": "Interstellar",
        "genre_ids": [
            12,
            18,
            878
        ],
        "backdrop_path": "/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
        "adult": false,
        "overview": "Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
        "release_date": "2014-11-05"
    },
    {
        "vote_count": 1388,
        "id": 315837,
        "video": false,
        "vote_average": 5.9,
        "title": "Ghost in the Shell",
        "popularity": 20.404081,
        "poster_path": "/si1ZyELNHdPUZw4pXR5KjMIIsBF.jpg",
        "original_language": "en",
        "original_title": "Ghost in the Shell",
        "genre_ids": [
            28,
            80,
            18,
            9648,
            878,
            53
        ],
        "backdrop_path": "/lsRhmB7m36pEX0UHpkpJSE48BW5.jpg",
        "adult": false,
        "overview": "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
        "release_date": "2017-03-29"
    },
    {
        "vote_count": 302,
        "id": 339403,
        "video": false,
        "vote_average": 6.6,
        "title": "Baby Driver",
        "popularity": 18.994133,
        "poster_path": "/mBkOBaxjr7IBHGuQS3sSFeyYTM.jpg",
        "original_language": "en",
        "original_title": "Baby Driver",
        "genre_ids": [
            28,
            80
        ],
        "backdrop_path": "/RMjc2RAxfsi4lOq7zb8NKB10NT.jpg",
        "adult": false,
        "overview": "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.",
        "release_date": "2017-06-28"
    },
    {
        "vote_count": 3340,
        "id": 381288,
        "video": false,
        "vote_average": 6.9,
        "title": "Split",
        "popularity": 18.225525,
        "poster_path": "/rXMWOZiCt6eMX22jWuTOSdQ98bY.jpg",
        "original_language": "en",
        "original_title": "Split",
        "genre_ids": [
            27,
            53
        ],
        "backdrop_path": "/4G6FNNLSIVrwSRZyFs91hQ3lZtD.jpg",
        "adult": false,
        "overview": "Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.",
        "release_date": "2016-11-15"
    },
    {
        "vote_count": 4898,
        "id": 131631,
        "video": false,
        "vote_average": 6.6,
        "title": "The Hunger Games: Mockingjay - Part 1",
        "popularity": 17.726471,
        "poster_path": "/gj282Pniaa78ZJfbaixyLXnXEDI.jpg",
        "original_language": "en",
        "original_title": "The Hunger Games: Mockingjay - Part 1",
        "genre_ids": [
            878,
            12,
            53
        ],
        "backdrop_path": "/4PwyB0ErucIANzW24Kori71J6gU.jpg",
        "adult": false,
        "overview": "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
        "release_date": "2014-11-18"
    },
    {
        "vote_count": 2157,
        "id": 324552,
        "video": false,
        "vote_average": 6.6,
        "title": "John Wick: Chapter 2",
        "popularity": 17.593787,
        "poster_path": "/zkXnKIwX5pYorKJp2fjFSfNyKT0.jpg",
        "original_language": "en",
        "original_title": "John Wick: Chapter 2",
        "genre_ids": [
            53,
            28,
            80
        ],
        "backdrop_path": "/dQ6s3Ud2KoOs3LKw6xgZr1cw7Yq.jpg",
        "adult": false,
        "overview": "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
        "release_date": "2017-02-08"
    },
    {
        "vote_count": 3529,
        "id": 228150,
        "video": false,
        "vote_average": 7.4,
        "title": "Fury",
        "popularity": 17.166059,
        "poster_path": "/pfte7wdMobMF4CVHuOxyu6oqeeA.jpg",
        "original_language": "en",
        "original_title": "Fury",
        "genre_ids": [
            10752,
            18,
            28
        ],
        "backdrop_path": "/pKawqrtCBMmxarft7o1LbEynys7.jpg",
        "adult": false,
        "overview": "Last months of World War II in April 1945. As the Allies make their final push in the European Theater, a battle-hardened U.S. Army sergeant in the 2nd Armored Division named Wardaddy commands a Sherman tank called \"Fury\" and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
        "release_date": "2014-10-15"
    },
    {
        "vote_count": 9319,
        "id": 293660,
        "video": false,
        "vote_average": 7.3,
        "title": "Deadpool",
        "popularity": 16.768299,
        "poster_path": "/inVq3FRqcYIRl2la8iZikYYxFNR.jpg",
        "original_language": "en",
        "original_title": "Deadpool",
        "genre_ids": [
            28,
            12,
            35,
            10749
        ],
        "backdrop_path": "/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg",
        "adult": false,
        "overview": "Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
        "release_date": "2016-02-09"
    },
    {
        "vote_count": 3708,
        "id": 211672,
        "video": false,
        "vote_average": 6.4,
        "title": "Minions",
        "popularity": 16.752306,
        "poster_path": "/q0R4crx2SehcEEQEkYObktdeFy.jpg",
        "original_language": "en",
        "original_title": "Minions",
        "genre_ids": [
            10751,
            16,
            12,
            35
        ],
        "backdrop_path": "/uX7LXnsC7bZJZjn048UCOwkPXWJ.jpg",
        "adult": false,
        "overview": "Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.",
        "release_date": "2015-06-17"
    },
    {
        "vote_count": 2420,
        "id": 283366,
        "video": false,
        "vote_average": 6.5,
        "title": "Miss Peregrine's Home for Peculiar Children",
        "popularity": 16.504063,
        "poster_path": "/AvekzUdI8HZnImdQulmTTmAZXrC.jpg",
        "original_language": "en",
        "original_title": "Miss Peregrine's Home for Peculiar Children",
        "genre_ids": [
            18,
            14,
            12
        ],
        "backdrop_path": "/9BVHn78oQcFCRd4M3u3NT7OrhTk.jpg",
        "adult": false,
        "overview": "A teenager finds himself transported to an island where he must help protect a group of orphans with special powers from creatures intent on destroying them.",
        "release_date": "2016-09-28"
    },
    {
        "vote_count": 3664,
        "id": 244786,
        "video": false,
        "vote_average": 8.3,
        "title": "Whiplash",
        "popularity": 15.736648,
        "poster_path": "/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg",
        "original_language": "en",
        "original_title": "Whiplash",
        "genre_ids": [
            10402,
            18
        ],
        "backdrop_path": "/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg",
        "adult": false,
        "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
        "release_date": "2014-10-10"
    },
    {
        "vote_count": 272,
        "id": 314095,
        "video": false,
        "vote_average": 6.1,
        "title": "The Lost City of Z",
        "popularity": 15.608846,
        "poster_path": "/uLHorVHuWQZ1HugTp0bbD19jef7.jpg",
        "original_language": "en",
        "original_title": "The Lost City of Z",
        "genre_ids": [
            28,
            12,
            18,
            36
        ],
        "backdrop_path": "/dAQzSsITJVxyk9ChqPLyBEwtGuC.jpg",
        "adult": false,
        "overview": "At the dawn of the 20th century, British explorer Percy Fawcett journeys into the Amazon, where he discovers evidence of a previously unknown, advanced civilization that may have once inhabited the region. Despite being ridiculed by the scientific establishment, which views indigenous populations as savages, the determined Fawcett, supported by his devoted wife, son, and aide-de-camp, returns to his beloved jungle in an attempt to prove his case.",
        "release_date": "2017-03-15"
    },
    {
        "vote_count": 6229,
        "id": 271110,
        "video": false,
        "vote_average": 7,
        "title": "Captain America: Civil War",
        "popularity": 15.521884,
        "poster_path": "/kSBXou5Ac7vEqKd97wotJumyJvU.jpg",
        "original_language": "en",
        "original_title": "Captain America: Civil War",
        "genre_ids": [
            12,
            28,
            878
        ],
        "backdrop_path": "/m5O3SZvQ6EgD5XXXLPIP1wLppeW.jpg",
        "adult": false,
        "overview": "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
        "release_date": "2016-04-27"
    },
    {
        "vote_count": 4622,
        "id": 329865,
        "video": false,
        "vote_average": 7,
        "title": "Arrival",
        "popularity": 14.956168,
        "poster_path": "/hLudzvGfpi6JlwUnsNhXwKKg4j.jpg",
        "original_language": "en",
        "original_title": "Arrival",
        "genre_ids": [
            53,
            18,
            878,
            9648
        ],
        "backdrop_path": "/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg",
        "adult": false,
        "overview": "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
        "release_date": "2016-11-10"
    },
    {
        "vote_count": 4273,
        "id": 122917,
        "video": false,
        "vote_average": 7.1,
        "title": "The Hobbit: The Battle of the Five Armies",
        "popularity": 14.53194,
        "poster_path": "/9zRzFJuaj0CHIOhAkcCcFTvyu2X.jpg",
        "original_language": "en",
        "original_title": "The Hobbit: The Battle of the Five Armies",
        "genre_ids": [
            28,
            12,
            14
        ],
        "backdrop_path": "/9tgt63Gk2C0Pu5Q8fkVO1TZuqW9.jpg",
        "adult": false,
        "overview": "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
        "release_date": "2014-12-10"
    },
    {
        "vote_count": 4535,
        "id": 284052,
        "video": false,
        "vote_average": 7,
        "title": "Doctor Strange",
        "popularity": 14.290434,
        "poster_path": "/4PiiNGXj1KENTmCBHeN6Mskj2Fq.jpg",
        "original_language": "en",
        "original_title": "Doctor Strange",
        "genre_ids": [
            28,
            12,
            14,
            878
        ],
        "backdrop_path": "/tFI8VLMgSTTU38i8TIsklfqS9Nl.jpg",
        "adult": false,
        "overview": "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under his wing and trains him to defend the world against evil.",
        "release_date": "2016-10-25"
    },
    {
        "vote_count": 5935,
        "id": 99861,
        "video": false,
        "vote_average": 7.3,
        "title": "Avengers: Age of Ultron",
        "popularity": 14.120647,
        "poster_path": "/t90Y3G8UGQp0f0DrP60wRu9gfrH.jpg",
        "original_language": "en",
        "original_title": "Avengers: Age of Ultron",
        "genre_ids": [
            28,
            12,
            878
        ],
        "backdrop_path": "/570qhjGZmGPrBGnfx70jcwIuBr4.jpg",
        "adult": false,
        "overview": "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
        "release_date": "2015-04-22"
    },
    {
        "vote_count": 2029,
        "id": 419430,
        "video": false,
        "vote_average": 7.1,
        "title": "Get Out",
        "popularity": 13.963615,
        "poster_path": "/1SwAVYpuLj8KsHxllTF8Dt9dSSX.jpg",
        "original_language": "en",
        "original_title": "Get Out",
        "genre_ids": [
            9648,
            53,
            27
        ],
        "backdrop_path": "/bBQHALHRAaaORlPNXv7fNcRXYdx.jpg",
        "adult": false,
        "overview": "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
        "release_date": "2017-02-24"
    },
    {
        "vote_count": 2794,
        "id": 91314,
        "video": false,
        "vote_average": 5.8,
        "title": "Transformers: Age of Extinction",
        "popularity": 13.368948,
        "poster_path": "/ykIZB9dYBIKV13k5igGFncT5th6.jpg",
        "original_language": "en",
        "original_title": "Transformers: Age of Extinction",
        "genre_ids": [
            878,
            28,
            12
        ],
        "backdrop_path": "/cHy7nSitAVgvZ7qfCK4JO47t3oZ.jpg",
        "adult": false,
        "overview": "As humanity picks up the pieces, following the conclusion of \"Transformers: Dark of the Moon,\" Autobots and Decepticons have all but vanished from the face of the planet. However, a group of powerful, ingenious businessman and scientists attempt to learn from past Transformer incursions and push the boundaries of technology beyond what they can control - all while an ancient, powerful Transformer menace sets Earth in his cross-hairs.",
        "release_date": "2014-06-25"
    },
    {
        "vote_count": 10545,
        "id": 19995,
        "video": false,
        "vote_average": 7.2,
        "title": "Avatar",
        "popularity": 13.22167,
        "poster_path": "/kmcqlZGaSh20zpTbuoF0Cdn07dT.jpg",
        "original_language": "en",
        "original_title": "Avatar",
        "genre_ids": [
            28,
            12,
            14,
            878
        ],
        "backdrop_path": "/xSxlmtLz2NYtO07N4WexY1y53pl.jpg",
        "adult": false,
        "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
        "release_date": "2009-12-10"
    },
    {
        "vote_count": 6163,
        "id": 209112,
        "video": false,
        "vote_average": 5.6,
        "title": "Batman v Superman: Dawn of Justice",
        "popularity": 13.133155,
        "poster_path": "/cGOPbv9wA5gEejkUN892JrveARt.jpg",
        "original_language": "en",
        "original_title": "Batman v Superman: Dawn of Justice",
        "genre_ids": [
            28,
            12,
            14
        ],
        "backdrop_path": "/vsjBeMPZtyB7yNsYY56XYxifaQZ.jpg",
        "adult": false,
        "overview": "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
        "release_date": "2016-03-23"
    },
    {
        "vote_count": 10810,
        "id": 155,
        "video": false,
        "vote_average": 8.2,
        "title": "The Dark Knight",
        "popularity": 13.021997,
        "poster_path": "/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg",
        "original_language": "en",
        "original_title": "The Dark Knight",
        "genre_ids": [
            18,
            28,
            80,
            53
        ],
        "backdrop_path": "/nnMC0BM6XbjIIrT4miYmMtPGcQV.jpg",
        "adult": false,
        "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        "release_date": "2008-07-16"
    },
    {
        "vote_count": 629,
        "id": 339846,
        "video": false,
        "vote_average": 5.7,
        "title": "Baywatch",
        "popularity": 12.98828,
        "poster_path": "/6HE4xd8zloDqmjMZuhUCCw2UcY1.jpg",
        "original_language": "en",
        "original_title": "Baywatch",
        "genre_ids": [
            28,
            35
        ],
        "backdrop_path": "/tryI7qZHaLMVzMNpLyKHKDiZOLc.jpg",
        "adult": false,
        "overview": "Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit. Together, they uncover a local criminal plot that threatens the future of the Bay.",
        "release_date": "2017-05-12"
    },
    {
        "vote_count": 4326,
        "id": 259316,
        "video": false,
        "vote_average": 7.1,
        "title": "Fantastic Beasts and Where to Find Them",
        "popularity": 12.802148,
        "poster_path": "/1M91Bt3oGspda75H9eLqYZkJzgO.jpg",
        "original_language": "en",
        "original_title": "Fantastic Beasts and Where to Find Them",
        "genre_ids": [
            10751,
            14
        ],
        "backdrop_path": "/6I2tPx6KIiBB4TWFiWwNUzrbxUn.jpg",
        "adult": false,
        "overview": "In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations.",
        "release_date": "2016-11-16"
    },
    {
        "vote_count": 313,
        "id": 339988,
        "video": false,
        "vote_average": 5.2,
        "title": "The Circle",
        "popularity": 12.776301,
        "poster_path": "/bQVqd5rWrx5GbXhJNuvKy4Viz6j.jpg",
        "original_language": "en",
        "original_title": "The Circle",
        "genre_ids": [
            18,
            53,
            878
        ],
        "backdrop_path": "/hENBbG0J4zf4fFB3OVAC50poojR.jpg",
        "adult": false,
        "overview": "A young tech worker takes a job at a powerful Internet corporation, quickly rises up the company's ranks, and soon finds herself in a perilous situation concerning privacy, surveillance and freedom. She comes to learn that her decisions and actions will determine the future of humanity.",
        "release_date": "2017-04-27"
    },
    {
        "vote_count": 4064,
        "id": 246655,
        "video": false,
        "vote_average": 6.3,
        "title": "X-Men: Apocalypse",
        "popularity": 12.747379,
        "poster_path": "/zSouWWrySXshPCT4t3UKCQGayyo.jpg",
        "original_language": "en",
        "original_title": "X-Men: Apocalypse",
        "genre_ids": [
            878
        ],
        "backdrop_path": "/oQWWth5AOtbWG9o8SCAviGcADed.jpg",
        "adult": false,
        "overview": "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
        "release_date": "2016-05-18"
    },
    {
        "vote_count": 3320,
        "id": 87101,
        "video": false,
        "vote_average": 5.8,
        "title": "Terminator Genisys",
        "popularity": 12.511513,
        "poster_path": "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
        "original_language": "en",
        "original_title": "Terminator Genisys",
        "genre_ids": [
            878,
            28,
            53,
            12
        ],
        "backdrop_path": "/bIlYH4l2AyYvEysmS2AOfjO7Dn8.jpg",
        "adult": false,
        "overview": "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
        "release_date": "2015-06-23"
    },
    {
        "vote_count": 5213,
        "id": 210577,
        "video": false,
        "vote_average": 7.9,
        "title": "Gone Girl",
        "popularity": 12.482372,
        "poster_path": "/gdiLTof3rbPDAmPaCf4g6op46bj.jpg",
        "original_language": "en",
        "original_title": "Gone Girl",
        "genre_ids": [
            9648,
            53,
            18
        ],
        "backdrop_path": "/bt6DhdALyhf90gReozoQ0y3R3vZ.jpg",
        "adult": false,
        "overview": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
        "release_date": "2014-10-01"
    },
    {
        "vote_count": 4584,
        "id": 58,
        "video": false,
        "vote_average": 6.9,
        "title": "Pirates of the Caribbean: Dead Man's Chest",
        "popularity": 12.41198,
        "poster_path": "/waFr5RVKaQ9dzOt3nQuIVB1FiPu.jpg",
        "original_language": "en",
        "original_title": "Pirates of the Caribbean: Dead Man's Chest",
        "genre_ids": [
            12,
            14,
            28
        ],
        "backdrop_path": "/hdHgIcljPHli4xaJGt0INz8Gn3J.jpg",
        "adult": false,
        "overview": "Captain Jack Sparrow works his way out of a blood debt with the ghostly Davey Jones, he also attempts to avoid eternal damnation.",
        "release_date": "2006-06-20"
    },
    {
        "vote_count": 10818,
        "id": 24428,
        "video": false,
        "vote_average": 7.4,
        "title": "The Avengers",
        "popularity": 12.233214,
        "poster_path": "/cezWGskPY5x7GaglTTRN4Fugfb8.jpg",
        "original_language": "en",
        "original_title": "The Avengers",
        "genre_ids": [
            878,
            28,
            12
        ],
        "backdrop_path": "/hbn46fQaRmlpBuUrEiFqv0GDL6Y.jpg",
        "adult": false,
        "overview": "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
        "release_date": "2012-04-25"
    },
    {
        "vote_count": 4880,
        "id": 205596,
        "video": false,
        "vote_average": 8,
        "title": "The Imitation Game",
        "popularity": 12.138146,
        "poster_path": "/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg",
        "original_language": "en",
        "original_title": "The Imitation Game",
        "genre_ids": [
            36,
            18,
            53,
            10752
        ],
        "backdrop_path": "/qcb6z1HpokTOKdjqDTsnjJk0Xvg.jpg",
        "adult": false,
        "overview": "Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.",
        "release_date": "2014-11-14"
    },
    {
        "vote_count": 12460,
        "id": 27205,
        "video": false,
        "vote_average": 8,
        "title": "Inception",
        "popularity": 12.010943,
        "poster_path": "/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
        "original_language": "en",
        "original_title": "Inception",
        "genre_ids": [
            28,
            53,
            878,
            9648,
            12
        ],
        "backdrop_path": "/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg",
        "adult": false,
        "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
        "release_date": "2010-07-14"
    },
    {
        "vote_count": 5015,
        "id": 240832,
        "video": false,
        "vote_average": 6.2,
        "title": "Lucy",
        "popularity": 11.953107,
        "poster_path": "/rwn876MeqienhOVSSjtUPnwxn0Z.jpg",
        "original_language": "en",
        "original_title": "Lucy",
        "genre_ids": [
            28,
            878
        ],
        "backdrop_path": "/eCgIoGvfNXrbSiQGqQHccuHjQHm.jpg",
        "adult": false,
        "overview": "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
        "release_date": "2014-07-14"
    },
    {
        "vote_count": 3317,
        "id": 262500,
        "video": false,
        "vote_average": 6.2,
        "title": "Insurgent",
        "popularity": 11.916094,
        "poster_path": "/6w1VjTPTjTaA5oNvsAg0y4H6bou.jpg",
        "original_language": "en",
        "original_title": "Insurgent",
        "genre_ids": [
            12,
            878,
            53
        ],
        "backdrop_path": "/L5QRL1O3fGs2hH1LbtYyVl8Tce.jpg",
        "adult": false,
        "overview": "Beatrice Prior must confront her inner demons and continue her fight against a powerful alliance which threatens to tear her society apart.",
        "release_date": "2015-03-18"
    },
    {
        "vote_count": 5420,
        "id": 127585,
        "video": false,
        "vote_average": 7.6,
        "title": "X-Men: Days of Future Past",
        "popularity": 11.816698,
        "poster_path": "/qKkFk9HELmABpcPoc1HHZGIxQ5a.jpg",
        "original_language": "en",
        "original_title": "X-Men: Days of Future Past",
        "genre_ids": [
            28,
            12,
            14,
            878
        ],
        "backdrop_path": "/5kYj5EOQMFBFCdnk4X8KaFUfDVR.jpg",
        "adult": false,
        "overview": "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.",
        "release_date": "2014-05-15"
    },
    {
        "vote_count": 2534,
        "id": 324786,
        "video": false,
        "vote_average": 7.7,
        "title": "Hacksaw Ridge",
        "popularity": 11.744252,
        "poster_path": "/bndiUFfJxNd2fYx8XO610L9a07m.jpg",
        "original_language": "en",
        "original_title": "Hacksaw Ridge",
        "genre_ids": [
            18,
            36,
            10752
        ],
        "backdrop_path": "/zBK4QZONMQXhcgaJv1YYTdCW7q9.jpg",
        "adult": false,
        "overview": "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector in American history to win the Congressional Medal of Honor.",
        "release_date": "2016-10-07"
    },
    {
        "vote_count": 2368,
        "id": 98566,
        "video": false,
        "vote_average": 5.8,
        "title": "Teenage Mutant Ninja Turtles",
        "popularity": 11.669443,
        "poster_path": "/oDL2ryJ0sV2bmjgshVgJb3qzvwp.jpg",
        "original_language": "en",
        "original_title": "Teenage Mutant Ninja Turtles",
        "genre_ids": [
            878,
            28,
            12,
            14,
            35
        ],
        "backdrop_path": "/OqCXGt5nl1cHPeotxCDvXLLe6p.jpg",
        "adult": false,
        "overview": "The city needs heroes. Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April and her wise-cracking cameraman Vern Fenwick to save the city and unravel Shredder's diabolical plan.",
        "release_date": "2014-08-07"
    },
    {
        "vote_count": 4234,
        "id": 330459,
        "video": false,
        "vote_average": 7.4,
        "title": "Rogue One: A Star Wars Story",
        "popularity": 11.600596,
        "poster_path": "/qjiskwlV1qQzRCjpV0cL9pEMF9a.jpg",
        "original_language": "en",
        "original_title": "Rogue One: A Star Wars Story",
        "genre_ids": [
            12,
            878,
            28
        ],
        "backdrop_path": "/tZjVVIYXACV4IIIhXeIM59ytqwS.jpg",
        "adult": false,
        "overview": "A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.",
        "release_date": "2016-12-14"
    }
];
